# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: npm install
      - run: npm run build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: darwin-prebuild
          path: ./prebuilds/**/*

  build-linux:
    needs: build-macos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: npm install
      - run: npm run build
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: darwin-prebuild
      - run: npm pack
      - run: mv node-rdkafka-*.tgz node-rdkafka.tgz
      - name: Upload a Release Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: node-rdkafka.tgz
          asset_name: node-rdkafka
          asset_content_type: application/x-gtar
